# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b26b511c90bec3fea922dbd4b675f5470cb13e4c1137b2bbca1b107f25649900788365aee02ac7f3c9ad6ca9af609b8da00f6f6da6efc76901f885450e81931c

test:
  secret_key_base: 850abf30aa1ea30285a88122bfa5d972bc7aa79f2e359b7d7c935f02b92acbe30f4625fbd44f83885e12fcfb6aa307727b5da626049a3c012ce87549896e44e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
